= 線画抽出と着色 =
このサンプルは、ある画像からの線画抽出と、線画の着色をDeepLearningで学習してみるサンプル。

== 着色処理を説明してみる ==
着色処理の学習と着色処理について、DeepLearning部分とTensorflowの使い方を合わせて説明を試みる。

=== 着色の学習 ===
着色の学習を行うとして大事なのは、 *何を特徴変数とするか* である。着色を行う場合、最終的に出力されるデータは、入力された線画と同一のサイズでなければならない。

基本路線としては、AutoEncoderと呼ばれるものを作成することになる。AutoEncoderの定義は探す。

AutoEncoderの原理は、特徴量から元の画像を復元する、Decodingが肝となる。

. Convolution+max poolingを利用して特徴を抽出して、高解像度から多数の特徴を抽出する
. 抽出した特徴量から、deconvolutionで画像を復元する
. deconvolutionした画像と教師画像を、loglossと呼ばれる損失関数の値を最小化するように最適化する

loglossは最尤推定関数の一種。定義上、それぞれの種類ラベル毎に定義されている確率と、推定した確率のlogをかけたものの平均をとり、符号を反転させたものを指す。
推定した確率のlogを取っているのは、推定した確率をそのまま利用した場合、陽であると判定した確率が実際には偽であった場合、エラースコアが無限大になってしまい、他の確率が全て意味を成さなくなってしまう。
これを避けるため、わざとlogを取ることで、オーバーシュートを防ぐことを目的としている。

loglossとはこれ。
https://www.kaggle.com/wiki/LogarithmicLoss


本質的には、確率全体が保存され、全体がlabelからどれだけ離れているか、ということを定義している。

試しに計算してみる

label: 0.7,0.3
predict: 0.4, 0.6

0.7*log(0.4) + 0.3 * log(0.6) / 2 = -0.39

label:0.7,0.3
predict: 0.69,0.31

0.7*log(0.69) + 0.3 * log(0.31) / 2 = -0.30

確率が近づいてくると、0に近づく＝ロスが少なくなる、という判定ができる。同じ確率になったタイミングが一番小さい（値自体は0にならない）。

余程離れない限り、差は意外と小さくなることがわかる。


kerasを利用したautoencoderの実装。kerasでは損失関数の一つとして、loglossが用意されている。
https://blog.keras.io/building-autoencoders-in-keras.html

== Amazon LinuxでGPU利用する ==
CPUだけでやると時間がかかってしょうがない＋学習用データが大きすぎて洒落にならないため、クラウド環境で実施したい。
AzureでもGCPでもいいけれども、使い慣れてるAWSのGPUインスタンスを使ってみる（使ったことがなかった）。

まともに利用するとかなりの金額になりそうだったので、SpotFleetで用意しました。Spot Fleetになってから初めて利用しますが、ちゃんとドキュメントを読まないと、capacityの意味が？ってなりますね。

楽をするために、Ubuntu16.04のAMIを利用する。次に、CUDA/cuDNNのライブラリをダウンロードする。

CUDAライブラリは、runfileにしておくと楽。ただし今回はdebにしてしまったので、次のようになる。

[source, bash]
----
$ sudo dpkg -i <ダウンロードしたパッケージ名>
$ sudo apt-get update
$ sudo apt-get install cuda
----

cudnnライブラリは、cudaをインストールした先に展開する。debでインストールした場合は `/usr/local/lib/cuda` に入るので、その下になるように入れる。

[source, bash]
----
$ tar xf cudnn-*.tgz
$ sudo cp cuda/include/* /usr/local/cuda/include
$ sudo cp cuda/lib64/* /usr/local/cuda/lib64
----

[WARNING]
====
Tensorflowが1.0になったが、GPU版の要求CUDAが8.0（最新）になり、同時に要求されるnvidia-driverのバージョンが375系になった。

Tokyoリージョンで利用できるg2インスタンスだと、K520というインスタンスで、367.\*系のドライバでしか動かない・・・。そのため、tensorflowのバージョンを下げるか、USリージョンでp2インスタンスを利用する必要がある。
====

そして、LD_LIBRARY_PATHを設定する。これを忘れるとライブラリの読み込みでエラーになる。

..bash_profile
[source,shell]
----
if [[ -z $LD_LIBRARY_PATH ]]; then
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64
else
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
fi
----

